:bug: error prepaid gas on chapter 6 near101 - add --gas command
NEAR-Edu/near.academy pull request #10
Opened 2022-01-13 11:06 UTC by Maxvyr

Add --gas command inside the CLI commande example

2022-02-05 07:40 UTC, daniel-lee-tech commented
for more context why this is very important to merge in:

please merge this is, it's been open for over a month!

https://github.com/NEAR-Edu/near.academy/issues/11

2022-02-07 17:02 UTC, ryancwalsh requested changes
Thanks for submitting this PR!

I too had run into this problem in November when I was going through the Near.academy course myself.

I will approve and merge your PR if you decrease the gas to `--gas=75000000000000`
https://stackoverflow.com/a/70088891/470749

Thanks!

2022-02-08 16:33 UTC, ryancwalsh approved these changes

2022-02-08 16:33 UTC, merged

2022-02-08 16:36 UTC, ryancwalsh commented
@Maxvyr @daniel-lee-tech Thanks for this! It might be a few weeks more before the change goes live on the server because we're about to switch from one server location to another when we have a moment to do that.

It's great that your improvement is now in the development branch so will make it into the main branch and appear at that time.